export default {
  login: "David-Henery4",
  id: 75099025,
  node_id: "MDQ6VXNlcjc1MDk5MDI1",
  avatar_url: "https://avatars.githubusercontent.com/u/75099025?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/David-Henery4",
  html_url: "https://github.com/David-Henery4",
  followers_url: "https://api.github.com/users/David-Henery4/followers",
  following_url:
    "https://api.github.com/users/David-Henery4/following{/other_user}",
  gists_url: "https://api.github.com/users/David-Henery4/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/David-Henery4/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/David-Henery4/subscriptions",
  organizations_url: "https://api.github.com/users/David-Henery4/orgs",
  repos_url: "https://api.github.com/users/David-Henery4/repos",
  events_url: "https://api.github.com/users/David-Henery4/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/David-Henery4/received_events",
  type: "User",
  site_admin: false,
  name: "David Henery",
  company: null,
  blog: "https://www.djhwebdevelopment.com",
  location: "London",
  email: null,
  hireable: null,
  bio: "Hi, my names David, I'm frontend developer who loves learning new technologies and building things with those technologies.",
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-11-26T22:31:58Z",
  updated_at: "2022-06-13T17:09:30Z",
};
